### ISSUE TITLE
quantized model ? Llama cpp?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [vgel/repeng#2]
Hi,

Reading your articles made me really curious about trying that but I was wondering of it was possible to use HuggingFace's quantized models or even llamacpp or if that required deep changes.

Thanks!

**Comment by vgel** [comment]
Working on a llama.cpp implementation!

**Comment by vgel** [comment]
There's now a PR live on the llama.cpp repo: https://github.com/ggerganov/llama.cpp/pull/5970

**Comment by vgel** [comment]
That PR is merged, so closing this issue.
