### ISSUE TITLE
Q: repeng vs system prompt

### ISSUE THREAD

**Issue by nmandic78** [vgel/repeng#20]
This sounds like a cool idea! Watching your PR in llama.cpp.
I have just few questions. What is the difference in effect on generation when compared with system prompt? Stronger and/or more precise influence? Speed? Could multiple control vectors be combined? In series or in parallel?
Thank you!

**Comment by vgel** [comment]
I discuss this somewhat in the blog post here: https://vgel.me/posts/representation-engineering/#Control_Vectors_v.s._Prompt_Engineering , but it's worth testing with your specific task!

**Comment by nmandic78** [comment]
Thank you. Blog explains the gist very well. Should have red it at start, thanks for pointing to it. For other questions I should test it myself and I will. 
I see it as some kind of 'latent space' (embeddings and hidden states) navigation bias. Very interesting.
