### ISSUE TITLE
Control Vector Arithmetic

### ISSUE THREAD

**Issue by mory91** [vgel/repeng#3]
Hi,
First of all, I read your blog post and it was great! Thanks for that. 
I had an idea I wanted to see if you tried that or not. 
Did you try to control vector arithmetic? e.g. adding jealousy and wrath control vectors and getting a jealous angry llm.

**Comment by vgel** [comment]
Yeah that should be possible, planning to add it soon along with a notebook demonstration.

**Comment by vgel** [comment]
Added in #6 ! Happy to accept additional examples, you can either append to the `vector_ops` notebook or make `vector_ops_2` if what you have in mind is sufficiently different.
