### ISSUE TITLE
Where does the suffixes come from in the data folder?

### ISSUE THREAD

**Issue by LukasNel** [vgel/repeng#46]
Trying to apply this in a personal project, but confused as to where the output_suffixes are derived from and how you would modify them for use for ex. in a RAG chatbot.

**Comment by vgel** [comment]
They come from https://github.com/andyzoujm/representation-engineering/blob/main/data/emotions/all_truncated_outputs.json , but they aren't particularly important--you could use anything, the point is just to collect activations from after a few different suffixes so the vector doesn't overfit to a specific ending token. They shouldn't be domain dependent and should work fine for any application, though you could explore generating your own domain-specific ones to see if that improves performance.
