### ISSUE TITLE
Trying this out on llama3-8b , what range of layers do I use?

### ISSUE THREAD

**Issue by 7hacker** [vgel/repeng#48]
Hi, thanks for making this library - pretty cool!

I'm trying to modify the llama3-70b notebook to llama3-8b and hit the out of range when setting the layer ranges to use. 

```
wrapped_model = model
model = ControlModel(wrapped_model, list(range(20, 60)))
```

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-7-7cb59d37bf58>](https://localhost:8080/#) in <cell line: 2>()
      1 wrapped_model = model
----> 2 model = ControlModel(wrapped_model, list(range(20, 60)))

2 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py](https://localhost:8080/#) in _get_abs_string_index(self, idx)
    285         idx = operator.index(idx)
    286         if not (-len(self) <= idx < len(self)):
--> 287             raise IndexError(f'index {idx} is out of range')
    288         if idx < 0:
    289             idx += len(self)

IndexError: index 32 is out of range
```

llama3-8b has 32 total layers

```
num_layers = len(model.model.layers)  # Example for a specific model architecture
print(f"Number of layers: {num_layers}")
```

So I had two questions:
- how do i know which ranges to apply for llama3-8b ?
- why are these ranges chosen specifically , are they all the hidden layers ?

(I'm new to programming with pytorch and transformers )

**Comment by ujisati** [comment]
```python
    from repeng.control import model_layer_list
    layers = model_layer_list(model)
    print(len(layers))
    for i, layer in enumerate(layers):
        print(i, layer.__class__.__name__)
```

I'm no expert but I think the idea is you can experiment with whatever layers you want.

**Comment by thiswillbeyourgithub** [comment]
Btw I made a PR that added more intuitive ways to specify the layer ids

https://github.com/vgel/repeng/pull/55
https://github.com/vgel/repeng/pull/55/files

Also be careful to the template you use.

**Comment by vgel** [comment]
I generally use the middle ~2/3rds of layers--you just want to avoid the very early layers, which handle the inputs, and the very late layers, which handle the outputs. You roughly want to target the center "hump" in this graph (from `notebooks/sae.ipynb`)--imagine the X axis scaled to the layer range of your model:

![image](https://github.com/user-attachments/assets/979232c2-980b-4092-931d-97e4c8f7a113)

If you stick to that general principle, I haven't noticed big differences in the exact layer range targeted. @thiswillbeyourgithub 's PR is also a good place to look until that gets merged.
